namespace Ejar.Web.Store;

public class L
{
    private readonly AppStore _store;
    private readonly ITranslationProvider _provider;

    public L(AppStore store, ITranslationProvider provider)
    {
        _store = store;
        _provider = provider;
    }

    public string this[string key] => _provider.Translate(key, _store.Ui.Language);
    public bool IsRtl => _store.Ui.IsRtl;
    public string Lang => _store.Ui.Language;
}

public sealed class EmbeddedTranslationProvider : ITranslationProvider
{
    public string Translate(string key, string language)
    {
        if (language == "en" && En.TryGetValue(key, out var en)) return en;
        return Ar.TryGetValue(key, out var ar) ? ar : key;
    }

    private static readonly Dictionary<string, string> Ar = new()
    {
        ["app.name"] = "إيجار",
        ["common.search"] = "بحث",
        ["common.cancel"] = "إلغاء",
        ["common.save"] = "حفظ",
        ["common.submit"] = "تأكيد",
        ["common.retry"] = "إعادة المحاولة",
        ["common.close"] = "إغلاق",
        ["common.loading"] = "جارٍ التحميل…",
        ["common.empty"] = "لا توجد عناصر",
        ["common.next"] = "التالي",
        ["common.prev"] = "السابق",
        ["common.confirm"] = "تأكيد",
        ["common.all"] = "الكل",
        ["common.sar"] = "ريال",
        ["common.filter"] = "تصفية",
        ["common.reset"] = "إعادة تعيين",
        ["common.apply"] = "تطبيق",

        ["home.title"] = "ابحث عن عقارك المثالي",
        ["home.subtitle"] = "تطبيق الإيجار الأول في السعودية",
        ["home.search.placeholder"] = "ابحث عن شقة، فيلا، محل…",
        ["home.categories.title"] = "الفئات",
        ["home.featured.title"] = "إعلانات مميّزة",
        ["home.new.title"] = "أُضيف حديثاً",
        ["home.cta.title"] = "لديك عقار للإيجار؟",
        ["home.cta.subtitle"] = "أضف إعلانك الآن وابدأ بتأجير عقارك",
        ["home.view_all"] = "عرض الكل",
        ["home.city"] = "المدينة",

        ["nav.home"] = "الرئيسية",
        ["nav.search"] = "بحث",
        ["nav.favorites"] = "المفضلة",
        ["nav.chats"] = "الرسائل",
        ["nav.profile"] = "حسابي",
        ["nav.notifications"] = "الإشعارات",

        ["auth.login.title"] = "تسجيل الدخول",
        ["auth.phone"] = "رقم الجوّال",
        ["auth.otp"] = "رمز التحقق",
        ["auth.send_otp"] = "إرسال الرمز",
        ["auth.verify"] = "تحقّق",
        ["auth.signed_out"] = "تمّ تسجيل الخروج",
        ["auth.phone.hint"] = "أدخل رقم جوّالك للمتابعة",
        ["auth.otp.hint"] = "أدخل رمز التحقق المكوّن من 6 أرقام",
        ["auth.otp.demo"] = "رمز التجربة: 123456",
        ["auth.login.success"] = "تمّ تسجيل الدخول بنجاح",

        ["listing.amenities"] = "المرافق والخصائص",
        ["listing.description"] = "الوصف",
        ["listing.owner"] = "المُعلن",
        ["listing.no_results"] = "لا توجد إعلانات",
        ["listing.price"] = "السعر",
        ["listing.monthly"] = "شهرياً",
        ["listing.yearly"] = "سنوياً",
        ["listing.daily"] = "يومياً",
        ["listing.hourly"] = "بالساعة",
        ["listing.bedrooms"] = "غرف النوم",
        ["listing.area"] = "المساحة",
        ["listing.verified"] = "موثَّق",
        ["listing.views"] = "مشاهدة",
        ["listing.contact"] = "تواصل مع المُعلن",
        ["listing.favorite.add"] = "أضف للمفضلة",
        ["listing.favorite.remove"] = "أزل من المفضلة",
        ["listing.share"] = "مشاركة",

        ["listing.create.title"] = "أضف إعلانك",
        ["listing.create.field.title"] = "عنوان الإعلان",
        ["listing.create.field.description"] = "الوصف",
        ["listing.create.field.price"] = "السعر",
        ["listing.create.field.timeUnit"] = "وحدة الزمن",
        ["listing.create.field.city"] = "المدينة",
        ["listing.create.field.district"] = "الحيّ",
        ["listing.create.field.category"] = "نوع العقار",
        ["listing.create.field.bedrooms"] = "عدد غرف النوم",
        ["listing.create.field.bathrooms"] = "عدد دورات المياه",
        ["listing.create.field.area"] = "المساحة (م²)",

        ["filter.city"] = "المدينة",
        ["filter.district"] = "الحيّ",
        ["filter.type"] = "نوع العقار",
        ["filter.time_unit"] = "مدة الإيجار",
        ["filter.price_min"] = "أقل سعر",
        ["filter.price_max"] = "أعلى سعر",
        ["filter.sort"] = "الترتيب",
        ["filter.sort.views"] = "الأكثر مشاهدة",
        ["filter.sort.price_asc"] = "السعر: من الأقل",
        ["filter.sort.price_desc"] = "السعر: من الأعلى",

        ["chat.title"] = "المحادثات",
        ["chat.new_message"] = "اكتب رسالتك…",
        ["chat.send"] = "إرسال",
        ["chat.start"] = "بدء محادثة",
        ["chat.about_listing"] = "حول الإعلان",

        ["notification.title"] = "الإشعارات",
        ["notification.mark_read"] = "تحديد كمقروء",
        ["notification.mark_all_read"] = "تحديد الكل كمقروء",
        ["notification.empty"] = "لا توجد إشعارات",

        ["complaint.title"] = "الشكاوى",
        ["complaint.new"] = "شكوى جديدة",
        ["complaint.subject"] = "الموضوع",
        ["complaint.body"] = "التفاصيل",
        ["complaint.send"] = "إرسال",
        ["complaint.reply"] = "رد",
        ["complaint.status.open"] = "مفتوحة",
        ["complaint.status.resolved"] = "محلولة",
        ["complaint.status.closed"] = "مغلقة",

        ["plans.title"] = "الباقات والخطط",
        ["plans.subscribe"] = "اشترك الآن",
        ["plans.current"] = "الخطة الحالية",
        ["plans.listings_limit"] = "إعلان",
        ["plans.free"] = "مجاناً",

        ["subscription.title"] = "اشتراكي",
        ["subscription.days_remaining"] = "يوم متبقّي",
        ["subscription.renew"] = "تجديد",
        ["subscription.change"] = "تغيير الخطّة",
        ["subscription.invoices"] = "الفواتير",
        ["subscription.usage"] = "إعلانات مستخدمة",

        ["favorites.title"] = "المفضلة",
        ["favorites.empty"] = "لم تضف أي إعلان للمفضلة بعد",

        ["my_listings.title"] = "إعلاناتي",
        ["my_listings.add"] = "أضف إعلاناً",
        ["my_listings.empty"] = "لا توجد إعلانات بعد",
        ["my_listings.active"] = "نشط",
        ["my_listings.paused"] = "موقوف",
        ["my_listings.toggle"] = "تغيير الحالة",
        ["my_listings.delete"] = "حذف",

        ["profile.edit"] = "تعديل الملفّ الشخصيّ",
        ["profile.name"] = "الاسم الكامل",
        ["profile.phone"] = "رقم الجوّال",
        ["profile.email"] = "البريد الإلكتروني",
        ["profile.city"] = "المدينة",
        ["profile.verified"] = "موثَّق",
        ["profile.save"] = "حفظ التغييرات",

        ["settings.title"] = "الإعدادات",
        ["settings.theme"] = "السمة",
        ["settings.theme.light"] = "فاتح",
        ["settings.theme.dark"] = "داكن",
        ["settings.language"] = "اللغة",
        ["settings.sign_out"] = "تسجيل الخروج",

        ["legal.privacy"] = "سياسة الخصوصيّة",
        ["legal.terms"] = "الشروط والأحكام",
        ["legal.refund"] = "سياسة الاسترداد",

        ["version.required"] = "تحديث مطلوب",
        ["version.required_body"] = "يجب تحديث التطبيق للاستمرار في استخدامه",
        ["version.download"] = "تنزيل الإصدار الجديد",
        ["version.current"] = "الإصدار الحالي",
        ["version.latest"] = "الإصدار المتاح",

        ["help.title"] = "المساعدة والدعم",
        ["help.faq"] = "الأسئلة الشائعة",
        ["help.contact"] = "تواصل معنا",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["app.name"] = "Ejar",
        ["common.search"] = "Search",
        ["common.cancel"] = "Cancel",
        ["common.save"] = "Save",
        ["common.submit"] = "Submit",
        ["common.retry"] = "Retry",
        ["common.close"] = "Close",
        ["common.loading"] = "Loading…",
        ["common.empty"] = "No items",
        ["common.next"] = "Next",
        ["common.prev"] = "Previous",
        ["common.confirm"] = "Confirm",
        ["common.all"] = "All",
        ["common.sar"] = "SAR",
        ["common.filter"] = "Filter",
        ["common.reset"] = "Reset",
        ["common.apply"] = "Apply",

        ["home.title"] = "Find your perfect property",
        ["home.subtitle"] = "Saudi Arabia's #1 rental app",
        ["home.search.placeholder"] = "Search apartments, villas, shops…",
        ["home.categories.title"] = "Categories",
        ["home.featured.title"] = "Featured listings",
        ["home.new.title"] = "Newly added",
        ["home.cta.title"] = "Have a property to rent?",
        ["home.cta.subtitle"] = "Add your listing and start earning",
        ["home.view_all"] = "View all",
        ["home.city"] = "City",

        ["nav.home"] = "Home",
        ["nav.search"] = "Search",
        ["nav.favorites"] = "Favorites",
        ["nav.chats"] = "Messages",
        ["nav.profile"] = "Profile",
        ["nav.notifications"] = "Notifications",

        ["auth.login.title"] = "Sign In",
        ["auth.phone"] = "Phone number",
        ["auth.otp"] = "Verification code",
        ["auth.send_otp"] = "Send code",
        ["auth.verify"] = "Verify",
        ["auth.signed_out"] = "Signed out",
        ["auth.phone.hint"] = "Enter your phone number to continue",
        ["auth.otp.hint"] = "Enter the 6-digit verification code",
        ["auth.otp.demo"] = "Demo code: 123456",
        ["auth.login.success"] = "Signed in successfully",

        ["listing.amenities"] = "Amenities",
        ["listing.description"] = "Description",
        ["listing.owner"] = "Landlord",
        ["listing.no_results"] = "No listings found",
        ["listing.price"] = "Price",
        ["listing.monthly"] = "monthly",
        ["listing.yearly"] = "yearly",
        ["listing.daily"] = "daily",
        ["listing.hourly"] = "hourly",
        ["listing.bedrooms"] = "Bedrooms",
        ["listing.area"] = "Area",
        ["listing.verified"] = "Verified",
        ["listing.views"] = "views",
        ["listing.contact"] = "Contact landlord",
        ["listing.favorite.add"] = "Add to favorites",
        ["listing.favorite.remove"] = "Remove from favorites",
        ["listing.share"] = "Share",

        ["listing.create.title"] = "Add listing",
        ["listing.create.field.title"] = "Title",
        ["listing.create.field.description"] = "Description",
        ["listing.create.field.price"] = "Price",
        ["listing.create.field.timeUnit"] = "Rental period",
        ["listing.create.field.city"] = "City",
        ["listing.create.field.district"] = "District",
        ["listing.create.field.category"] = "Property type",
        ["listing.create.field.bedrooms"] = "Bedrooms",
        ["listing.create.field.bathrooms"] = "Bathrooms",
        ["listing.create.field.area"] = "Area (sqm)",

        ["filter.city"] = "City",
        ["filter.district"] = "District",
        ["filter.type"] = "Property type",
        ["filter.time_unit"] = "Rental period",
        ["filter.price_min"] = "Min price",
        ["filter.price_max"] = "Max price",
        ["filter.sort"] = "Sort",
        ["filter.sort.views"] = "Most viewed",
        ["filter.sort.price_asc"] = "Price: low to high",
        ["filter.sort.price_desc"] = "Price: high to low",

        ["chat.title"] = "Messages",
        ["chat.new_message"] = "Write a message…",
        ["chat.send"] = "Send",
        ["chat.start"] = "Start chat",
        ["chat.about_listing"] = "About listing",

        ["notification.title"] = "Notifications",
        ["notification.mark_read"] = "Mark as read",
        ["notification.mark_all_read"] = "Mark all as read",
        ["notification.empty"] = "No notifications",

        ["complaint.title"] = "Complaints",
        ["complaint.new"] = "New complaint",
        ["complaint.subject"] = "Subject",
        ["complaint.body"] = "Details",
        ["complaint.send"] = "Submit",
        ["complaint.reply"] = "Reply",
        ["complaint.status.open"] = "Open",
        ["complaint.status.resolved"] = "Resolved",
        ["complaint.status.closed"] = "Closed",

        ["plans.title"] = "Plans & Pricing",
        ["plans.subscribe"] = "Subscribe now",
        ["plans.current"] = "Current plan",
        ["plans.listings_limit"] = "listing",
        ["plans.free"] = "Free",

        ["subscription.title"] = "My Subscription",
        ["subscription.days_remaining"] = "days remaining",
        ["subscription.renew"] = "Renew",
        ["subscription.change"] = "Change plan",
        ["subscription.invoices"] = "Invoices",
        ["subscription.usage"] = "Listings used",

        ["favorites.title"] = "Favorites",
        ["favorites.empty"] = "No favorites yet",

        ["my_listings.title"] = "My Listings",
        ["my_listings.add"] = "Add listing",
        ["my_listings.empty"] = "No listings yet",
        ["my_listings.active"] = "Active",
        ["my_listings.paused"] = "Paused",
        ["my_listings.toggle"] = "Toggle status",
        ["my_listings.delete"] = "Delete",

        ["profile.edit"] = "Edit profile",
        ["profile.name"] = "Full name",
        ["profile.phone"] = "Phone",
        ["profile.email"] = "Email",
        ["profile.city"] = "City",
        ["profile.verified"] = "Verified",
        ["profile.save"] = "Save changes",

        ["settings.title"] = "Settings",
        ["settings.theme"] = "Theme",
        ["settings.theme.light"] = "Light",
        ["settings.theme.dark"] = "Dark",
        ["settings.language"] = "Language",
        ["settings.sign_out"] = "Sign out",

        ["legal.privacy"] = "Privacy policy",
        ["legal.terms"] = "Terms of service",
        ["legal.refund"] = "Refund policy",

        ["version.required"] = "Update required",
        ["version.required_body"] = "Please update the app to continue",
        ["version.download"] = "Download latest",
        ["version.current"] = "Current version",
        ["version.latest"] = "Latest version",

        ["help.title"] = "Help & Support",
        ["help.faq"] = "FAQ",
        ["help.contact"] = "Contact us",
    };
}
